name: helody
description: A game.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.9.31
  animated_background: ^2.0.0
  meta: ^1.8.0
  file_picker: ^5.2.5
  file_selector: ^0.9.2+2
  path_provider: ^2.0.12
  archive: ^3.3.6
  cupertino_icons: ^1.0.5
  flame: ^1.6.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/avatar.png
    - images/logo.png
    - images/background.jpg
    - sounds/SongSelect.mp3
